spring.application.name=HR_Manager
spring.application.name=OneToManymapping
spring.datasource.url= jdbc:mysql://localhost:3306/springbootHR_Manager_?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true